import contextlib
import csv
import io
import os
import sqlite3
import sys
import tempfile
import unittest
import unittest.mock
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import finance_import


class FinanceImportTest(unittest.TestCase):
    def setUp(self):
        self.original_env = {
            "CONFIG_PATH": os.environ.get("CONFIG_PATH"),
            "DASHBOARD_DB_PATH": os.environ.get("DASHBOARD_DB_PATH"),
        }
        os.environ.pop("CONFIG_PATH", None)
        os.environ.pop("DASHBOARD_DB_PATH", None)

    def tearDown(self):
        for key, value in self.original_env.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value

    def test_finds_credit_card_header_after_preamble(self):
        with tempfile.TemporaryDirectory() as directory:
            csv_path = Path(directory) / "credit.csv"
            with csv_path.open("w", newline="") as handle:
                writer = csv.writer(handle)
                writer.writerow(["Export generated by bank"])
                writer.writerow(["Ignore", "this", "line"])
                writer.writerow(finance_import.CREDIT_CARD_HEADER)
                writer.writerow(["10/05/2026", "11/05/2026", "Lunch", "Sale", "Card", "Posted", "24.50", ""])

            rows = finance_import.read_statement_rows(
                csv_path,
                finance_import.STATEMENT_SPECS["credit"],
                "utf-8-sig",
            )

            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0][0], 4)
            self.assertEqual(rows[0][1]["Transaction Description"], "Lunch")

    def test_finds_debit_header_after_preamble(self):
        with tempfile.TemporaryDirectory() as directory:
            csv_path = Path(directory) / "debit.csv"
            with csv_path.open("w", newline="") as handle:
                writer = csv.writer(handle)
                writer.writerow(["Account history"])
                writer.writerow(finance_import.DEBIT_HEADER)
                writer.writerow(["10/05/2026", "POS", "Groceries", "", "", "", "Posted", "70.25", ""])

            rows = finance_import.read_statement_rows(
                csv_path,
                finance_import.STATEMENT_SPECS["debit"],
                "utf-8-sig",
            )

            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0][0], 3)
            self.assertEqual(rows[0][1]["Description"], "Groceries")

    def test_parse_credit_card_row_uses_relevant_fields_only(self):
        spec = finance_import.STATEMENT_SPECS["credit"]
        row = {
            "Transaction Date": "10/05/2026",
            "Transaction Posting Date": "11/05/2026",
            "Transaction Description": "Lunch",
            "Transaction Type": "Sale",
            "Payment Type": "Card",
            "Transaction Status": "Posted",
            "Debit Amount": "24.50",
            "Credit Amount": "",
        }

        item = finance_import.parse_import_row(4, row, spec)

        self.assertEqual(item.date, "2026-05-10")
        self.assertEqual(item.description, "Lunch")
        self.assertEqual(item.amount, -24.50)
        self.assertIsNone(item.category)

    def test_parse_debit_row_supports_credit_amount(self):
        spec = finance_import.STATEMENT_SPECS["debit"]
        row = {
            "Transaction Date": "10/05/2026",
            "Transaction Code": "GIRO",
            "Description": "Salary",
            "Transaction Ref1": "ignored",
            "Transaction Ref2": "ignored",
            "Transaction Ref3": "ignored",
            "Status": "Posted",
            "Debit Amount": "",
            "Credit Amount": "5000.00",
        }

        item = finance_import.parse_import_row(3, row, spec)

        self.assertEqual(item.date, "2026-05-10")
        self.assertEqual(item.description, "Salary")
        self.assertEqual(item.amount, 5000.00)

    def test_import_rows_inserts_into_current_schema(self):
        conn = self.open_test_db()
        category = finance_import.Category(id=1, name="Uncategorized", type="expense")
        spec = finance_import.STATEMENT_SPECS["credit"]
        raw_rows = [
            (
                4,
                {
                    "Transaction Date": "10/05/2026",
                    "Transaction Description": "Lunch",
                    "Debit Amount": "24.50",
                    "Credit Amount": "",
                },
            )
        ]

        stats = finance_import.import_rows(conn, raw_rows, spec, [category], category, accept_all=True)

        self.assertEqual(stats["imported"], 1)
        saved = conn.execute(
            "SELECT date, amount, category_id, description FROM finance_transactions"
        ).fetchone()
        self.assertEqual(saved, ("2026-05-10", -24.50, 1, "Lunch"))

    def test_yes_requires_category(self):
        with tempfile.TemporaryDirectory() as directory:
            db_path = Path(directory) / "dashboard.db"
            csv_path = Path(directory) / "credit.csv"
            self.open_test_db(db_path).close()
            with csv_path.open("w", newline="") as handle:
                writer = csv.writer(handle)
                writer.writerow(finance_import.CREDIT_CARD_HEADER)
                writer.writerow(["10/05/2026", "11/05/2026", "Lunch", "Sale", "Card", "Posted", "24.50", ""])

            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()) as error:
                code = finance_import.main_with_args(
                    [str(csv_path), "--db", str(db_path), "--transaction-type", "credit", "--yes"]
                )

            self.assertEqual(code, 1)
            self.assertIn("--yes requires --category", error.getvalue())

    def test_interactive_accept_prompts_for_required_category(self):
        conn = self.open_test_db()
        category = finance_import.Category(id=1, name="Uncategorized", type="expense")
        item = finance_import.ImportRow(
            source_line=4,
            date="2026-05-10",
            description="Lunch",
            amount=-24.50,
            category=None,
        )

        with unittest.mock.patch("builtins.input", side_effect=["a", "1"]):
            with contextlib.redirect_stdout(io.StringIO()):
                action = finance_import.review_row(conn, item, [category], duplicate=False)

        self.assertEqual(action, "accept")
        self.assertEqual(item.category, category)

    def test_category_shortcuts_include_tenth_category_without_enter(self):
        categories = [
            finance_import.Category(id=index, name=f"Category {index}", type="expense")
            for index in range(1, 11)
        ]

        shortcuts = finance_import.category_shortcuts(categories)

        self.assertEqual(shortcuts[1], "1")
        self.assertEqual(shortcuts[9], "9")
        self.assertEqual(shortcuts[10], "0")
        self.assertEqual(
            finance_import.category_by_shortcut(categories, shortcuts, "0"),
            categories[9],
        )

    def test_prepare_working_csv_copies_next_to_source(self):
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "statement.csv"
            source.write_text("metadata\n", encoding="utf-8")

            with contextlib.redirect_stdout(io.StringIO()):
                working = finance_import.prepare_working_csv(source)

            self.assertEqual(working, Path(directory) / "statement_dashboard.csv")
            self.assertTrue(working.exists())
            self.assertEqual(source.read_text(encoding="utf-8"), "metadata\n")

    def test_import_rows_consumes_accepted_lines_from_working_copy(self):
        with tempfile.TemporaryDirectory() as directory:
            working = Path(directory) / "statement_dashboard.csv"
            with working.open("w", newline="") as handle:
                writer = csv.writer(handle)
                writer.writerow(["metadata"])
                writer.writerow(finance_import.CREDIT_CARD_HEADER)
                writer.writerow(["10/05/2026", "11/05/2026", "Lunch", "Sale", "Card", "Posted", "24.50", ""])
                writer.writerow(["11/05/2026", "12/05/2026", "Dinner", "Sale", "Card", "Posted", "12.00", ""])

            conn = self.open_test_db()
            category = finance_import.Category(id=1, name="Uncategorized", type="expense")
            raw_rows = finance_import.read_statement_rows(
                working,
                finance_import.STATEMENT_SPECS["credit"],
                "utf-8-sig",
            )

            stats = finance_import.import_rows(
                conn,
                raw_rows,
                finance_import.STATEMENT_SPECS["credit"],
                [category],
                category,
                accept_all=True,
                consume_path=working,
            )

            self.assertEqual(stats["imported"], 2)
            remaining = working.read_text(encoding="utf-8")
            self.assertIn("Transaction Date", remaining)
            self.assertNotIn("Lunch", remaining)
            self.assertNotIn("Dinner", remaining)

    def test_cli_imports_selected_statement_type(self):
        with tempfile.TemporaryDirectory() as directory:
            db_path = Path(directory) / "dashboard.db"
            csv_path = Path(directory) / "credit.csv"
            self.open_test_db(db_path).close()
            with csv_path.open("w", newline="") as handle:
                writer = csv.writer(handle)
                writer.writerow(["metadata"])
                writer.writerow(finance_import.CREDIT_CARD_HEADER)
                writer.writerow(["10/05/2026", "11/05/2026", "Lunch", "Sale", "Card", "Posted", "24.50", ""])

            with contextlib.redirect_stdout(io.StringIO()):
                code = finance_import.main_with_args(
                    [
                        str(csv_path),
                        "--db",
                        str(db_path),
                        "--transaction-type",
                        "credit",
                        "--yes",
                        "--category",
                        "Uncategorized",
                    ]
                )

            self.assertEqual(code, 0)
            with sqlite3.connect(db_path) as conn:
                count = conn.execute("SELECT COUNT(*) FROM finance_transactions").fetchone()[0]
            self.assertEqual(count, 1)

    def test_cli_uses_dashboard_db_path_from_env_file(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            db_dir = root / "db"
            db_dir.mkdir()
            db_path = db_dir / "dashboard.db"
            env_path = root / ".env"
            csv_path = root / "credit.csv"
            self.open_test_db(db_path).close()

            env_path.write_text(
                f"CONFIG_PATH={db_dir}\nDASHBOARD_DB_PATH=${{CONFIG_PATH}}/dashboard.db\n",
                encoding="utf-8",
            )
            with csv_path.open("w", newline="") as handle:
                writer = csv.writer(handle)
                writer.writerow(finance_import.CREDIT_CARD_HEADER)
                writer.writerow(["10/05/2026", "11/05/2026", "Lunch", "Sale", "Card", "Posted", "24.50", ""])

            with contextlib.redirect_stdout(io.StringIO()):
                code = finance_import.main_with_args(
                    [
                        str(csv_path),
                        "--env-file",
                        str(env_path),
                        "--transaction-type",
                        "credit",
                        "--yes",
                        "--category",
                        "Uncategorized",
                    ]
                )

            self.assertEqual(code, 0)
            with sqlite3.connect(db_path) as conn:
                count = conn.execute("SELECT COUNT(*) FROM finance_transactions").fetchone()[0]
            self.assertEqual(count, 1)

    def open_test_db(self, path=None):
        conn = sqlite3.connect(path or ":memory:")
        conn.executescript(
            """
            CREATE TABLE finance_categories (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL UNIQUE,
                type TEXT NOT NULL
            );
            CREATE TABLE finance_transactions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                date TEXT NOT NULL,
                amount REAL NOT NULL,
                category_id INTEGER REFERENCES finance_categories(id),
                description TEXT,
                created_at TEXT DEFAULT (datetime('now'))
            );
            INSERT INTO finance_categories (name, type) VALUES ('Uncategorized', 'expense');
            """
        )
        return conn


if __name__ == "__main__":
    unittest.main()
